In [1]:
print('Hello There  Its Pytorch')

Hello There  Its Pytorch


In [2]:
!nvidia-smi

Fri Aug  4 02:35:25 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 00.Pytorch FUndamental

Resource notebook : https://www.learnpytorch.io/

In [3]:
import torch
print(torch.__version__)

2.0.1+cu118


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating tensors

In [5]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

#### For any help on torch.tensor
checkout : https://pytorch.org/docs/stable/tensors.html

In [6]:
scalar.ndim #Checking the dimension of scalar

0

In [7]:
scalar.item() #Get the tensor back as python int

7

In [8]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim #checkning the dimension of vector

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#matrix

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TORCH1 = torch.tensor([[[[1,2,3],[4,5,6],[7,8,9],[11,22,33]]]])
TORCH1

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [11, 22, 33]]]])

In [20]:
TORCH1.ndim

4

In [21]:
TORCH1.shape

torch.Size([1, 1, 4, 3])

In [22]:
TORCH1[0]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 22, 33]]])

### Random Tensors

Why Random Tensors?
.. Random tensors are important because the way many neural networs learns is that they start with tensors full of random numbers and then adjust those random numbers to be better represent the data.

`Start with random numbers -> Look at the data -> update random numbers -> look at the data --> update numbers`

Torch Random Tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0624, 0.4585, 0.0545, 0.7639],
        [0.4654, 0.1262, 0.1117, 0.8270],
        [0.5442, 0.4825, 0.5308, 0.3276]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor1 = torch.rand(2, 10, 10)
random_tensor1

tensor([[[8.4974e-02, 8.8624e-01, 8.0208e-01, 9.6752e-01, 3.4254e-01,
          3.0470e-01, 5.0861e-01, 6.1176e-01, 8.8492e-01, 1.7497e-01],
         [3.6713e-01, 1.6574e-01, 2.2266e-01, 7.5485e-01, 2.0920e-02,
          7.6599e-01, 2.8817e-01, 1.0332e-01, 6.6305e-01, 9.8175e-01],
         [7.7049e-01, 6.0633e-02, 8.7963e-01, 1.2191e-01, 4.7405e-01,
          2.6759e-01, 9.5049e-01, 3.6820e-01, 7.4437e-01, 3.4188e-02],
         [6.0024e-01, 1.6561e-01, 1.5153e-01, 4.7034e-01, 1.0076e-01,
          9.0875e-01, 6.4174e-01, 2.9981e-02, 9.9878e-01, 2.0605e-01],
         [7.0825e-01, 2.7068e-01, 9.0618e-01, 7.6530e-01, 7.4885e-01,
          7.4021e-01, 1.5874e-01, 6.6128e-01, 8.0545e-01, 8.1422e-01],
         [5.7866e-01, 5.9729e-02, 3.1304e-02, 9.5912e-02, 2.0265e-01,
          6.4682e-02, 1.7391e-01, 9.9885e-01, 9.2740e-01, 5.6296e-01],
         [1.6473e-01, 1.2689e-01, 4.0073e-01, 4.1059e-01, 2.3790e-01,
          3.4891e-01, 4.9845e-01, 4.5670e-01, 6.2672e-01, 7.7116e-01],
         [4.9

In [26]:
random_tensor1.ndim

3

In [27]:
#Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [28]:
torch.rand(3,3)

tensor([[0.7351, 0.2065, 0.1541],
        [0.6249, 0.7049, 0.8047],
        [0.2989, 0.4076, 0.4325]])

In [29]:
torch.rand(size=(3,3,3))

tensor([[[0.5230, 0.3065, 0.8155],
         [0.9745, 0.9620, 0.5640],
         [0.1002, 0.8006, 0.0962]],

        [[0.5973, 0.1136, 0.0955],
         [0.9173, 0.7861, 0.5442],
         [0.7909, 0.1619, 0.4859]],

        [[0.1098, 0.1777, 0.7720],
         [0.4576, 0.8838, 0.7162],
         [0.9988, 0.7004, 0.0915]]])

## Zeros and Ones

In [30]:
#Create a tensor of all zeros
zero = torch.zeros(size=(9,4))

In [31]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
#Create tensors of all ones
ones = torch.ones(size=(9,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
ones.dtype


torch.float32

### Create a rang of tensors and tensors-like

In [34]:
torch.arange(0,11) #torch.range #torch.arange

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
torch.__version__

'2.0.1+cu118'

In [36]:
one_to_ten = torch.arange(start =1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data-types

**Note:** Tensor datatypes are one of the 3 big errors with PyTorch & deep learning

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on right device

In [38]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What kind of datatype float 32 , 16
                               device=None, #What device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_32_tensor.dtype

torch.float32

In [40]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [42]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [43]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

Note: Tensor datatypes are one of the 3 big errors with PyTorch & deep learning

1. Tensors not right datatypes - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [44]:
#Create atensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1055, 0.7580, 0.0721, 0.2794],
        [0.7439, 0.0968, 0.0772, 0.7132],
        [0.7632, 0.0315, 0.2411, 0.0140]])

In [45]:
#find out details from some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype} ")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Size of a tensor : {some_tensor.size()}")
#shape is an attribute and size is a function or method, shape are coded without any brances while size being a function needs to be coded using ()
print(f"Device tensor is on : {some_tensor.device}")


tensor([[0.1055, 0.7580, 0.0721, 0.2794],
        [0.7439, 0.0968, 0.0772, 0.7132],
        [0.7632, 0.0315, 0.2411, 0.0140]])
Datatype of tensor : torch.float32 
Shape of tensor : torch.Size([3, 4])
Size of a tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operation)

Tensor Operation include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [46]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [47]:
# Multiplication of tensor by tensor * 10
tensor * 10

tensor([10, 20, 30])

In [48]:
# Subtracting tensor
tensor - 10

tensor([-9, -8, -7])

In [49]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [51]:
# Element-wise multiplication
tensor

tensor([1, 2, 3])

# Matrix Multiplication
There are two main ways of performing multiplication in neural networks and deep learning.
1. Element-wise multiplication
2. Mtrix Multiplication (Dot Product)

More informstion on Mstrix Multiplication : https://www.mathsisfun.com/algebra/matrix-multiplying.html#:~:text=To%20show%20how%20many%20rows,often%20write%20rows%C3%97columns.&text=When%20we%20do%20multiplication%3A,columns%20as%20the%202nd%20matrix.

There are two main rules that performing matrix multiplication needs to satisfy:
`In order for matrix multiplication to be defined, the number of columns in the first matrix must be equal to the number of rows in the second matrix`
1. The **Inner dimensions** must match  :
* (3, 2) @ (3, 2) --> `won't work`
* (2, 3) @ (3, 2) --> `will work`
* (3, 2) @ (2, 3) --> `will work`

@ - Symbol for Matrix Multipliaction

2. The resulting matrix has the shape of the **Outer dimensions**

* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`



In [52]:
#torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) --> This through error

In [53]:
tensor * tensor

tensor([1, 4, 9])

In [54]:
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [55]:
# Matrix Multiplication
torch.matmul(tensor, #This is doing dot product
             tensor)

tensor(14)

In [56]:
tensor

tensor([1, 2, 3])

In [57]:
# Multiplication by hand
1*1 + 2*2 + 3*3

14

In [58]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
value
print(value)

tensor(14)
CPU times: user 450 µs, sys: 0 ns, total: 450 µs
Wall time: 457 µs


In [59]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 41.5 µs


tensor(14)

#### One of the most common errors in the deep learnings
--> Shape Error


In [60]:
# Shapes for the matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

In [61]:
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [62]:
#torch.mm(tensor_A, tensor_B)  #torch.matmul is same as torch.mm (it's an alias)

# This would give an error `RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)'

In [63]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix tensor shape issue we can manipulate the shape of one of our tensors using a **transpose**

Transpose is change rows to columns and vice-versa

In [64]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [65]:
torch.mm(tensor_B, tensor_B.T)

tensor([[149, 166, 183],
        [166, 185, 204],
        [183, 204, 225]])

In [66]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes : tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimesnions must match")
print("Output : \n")
Output = torch.matmul(tensor_A, tensor_B.T)
print(f"\nOutput Shape : {Output.shape} ")
print(Output)
torch

Original shape : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes : tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimesnions must match
Output : 


Output Shape : torch.Size([3, 3]) 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


<module 'torch' from '/usr/local/lib/python3.10/dist-packages/torch/__init__.py'>

## Tensor Aggregation (min, max, mean, sum, etc)

In [67]:
#create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [69]:
# FInd the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [70]:
# Find the Average(mean) - note : torch.mean() fucntion requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [71]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [72]:
x.argmin() #FInd the position in tensor that has the minimum value with argmin() --> return index position of target tensor where minimum values occurs


tensor(0)

In [73]:
x[0]

tensor(0)

In [74]:
# Find the position in tensor that has the maximum value with argmax()

In [75]:
x.argmax()

tensor(9)

In [76]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a vies of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension to a target tensor
* Permute - Return a view of input with dimensions permuted (swapped) in a certain way

In [77]:
# Create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [78]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [80]:
#Changing the z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [81]:
# Stack function on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [82]:
# torch.squeeze() - remove all the single dimensions from a target tensor
x_reshaped
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

# Remove the extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor : {x_squeezed}")
print(f"New Shape : {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape : torch.Size([9])


In [83]:
# torch unsqueeze() - adds a single dimesnions to atarget tensor at a specific dim(dimension)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor : {x_unsqueezed}")
print(f"New Shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape : torch.Size([1, 9])


In [84]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
x_reshaped.squeeze().shape

torch.Size([9])

In [86]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x)
y.size()
torch.Size([2, 2, 2])
y = torch.squeeze(x, 0)
y.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x, 1)
y.size()
torch.Size([2, 2, 1, 2])
y = torch.squeeze(x, (1, 2, 3))
torch.Size([2, 2, 2])

torch.Size([2, 2, 2])

In [87]:
#Permute
#torch.permute -> rearranges the dimesions of a target tensor in a specified order
x_original = torch.rand(size=(224,229,3)) #[height, width, color_channels]

# Permute the origianl tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous Shape : {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") #[, height, width]

Previous Shape : torch.Size([224, 229, 3])
New Shape: torch.Size([3, 224, 229])


In [88]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

# Indexing (selecting Data from tesors)
Indexing with PyTorch is similar as to indexing with NumPy

In [89]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
# Lets index our new tesnor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
# Lets index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [92]:
# Lets index on inner bracket (last dimesnion)
x[0][0][0]

tensor(1)

In [93]:
x[0][2][2]

tensor(9)

In [94]:
# You can use : to selkect `all` target dimesnion
x[:, 0]

tensor([[1, 2, 3]])

In [95]:
# Get all values of 0th and 1st dimensions and only index 1 of 2nd dimesnions
x[:, :, 1]

tensor([[2, 5, 8]])

In [96]:
# Get all values of the 0th dimesnion but only the 1 index value of 1st and 2nd dimesnion
x[:, 1, 1]

tensor([5])

In [97]:
# Get Index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [98]:
# Index on x to return 9
print(x[:, 2, 2 ])

tensor([9])


In [99]:
# index to return 3, 6, 9
print(x[:, :, 2])


tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

NumPy is a popular python numerical library.

**Data** in `NumPy`, want in PyTorch tensor --> `tensor.from_numpy(ndarray)`
**Pytorch tensor** --> NumPY --> torch.Tensor.numpy()

In [100]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #Warning : when converting from numpy->pytorch, pytorch reflects numpy's default datatype float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [101]:
array.dtype

dtype('float64')

In [102]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [103]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [104]:
# Tesnor to NymPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [105]:
numpy_tensor.dtype

dtype('float32')

#### Note : default datatype of numpy is float-64 and default datatype of PyTorch is float-32

In [106]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> again`

To reduce the randomness in neural networks and pytorch comes with the concept of a **random seed**

Essentially what the random seed does is 'flavor' the randomness.

In [107]:
torch.rand(3, 3)


tensor([[0.8716, 0.8638, 0.6780],
        [0.8553, 0.1064, 0.2384],
        [0.9769, 0.8651, 0.4527]])

In [108]:
import torch
# Create two random tesnors
random_tensor_A =  torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8530, 0.5361, 0.6446, 0.7709],
        [0.9091, 0.7412, 0.9949, 0.4756],
        [0.1946, 0.3358, 0.6583, 0.3204]])
tensor([[0.4617, 0.0442, 0.3864, 0.7805],
        [0.7105, 0.0329, 0.8214, 0.3423],
        [0.5084, 0.5089, 0.8688, 0.9516]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [109]:
1 == 1

True

In [110]:
# Lets make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [111]:
## Extra Resources reproducibility : https://pytorch.org/docs/stable/notes/randomness.html

## Running Tensors and PyTorch objects on GPUs (and making faster computations)
GPUs = Faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to amke everything hunky dory(good)

### 1. Getting a GPU
1. Google Colab > Free GPU
2. Google COlab Pro > Paid
3. Google Colab Pro Plus > Paid (Higher Rate)
4. Use your youwn GPU (purchasing)
5. Use Cloud COmputing like GCP, Azure, AWS

In [112]:
!nvidia-smi

Fri Aug  4 02:35:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [113]:
## Check for GPU access with Pytorch
import torch
torch.cuda.is_available()


True

In [114]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [115]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tesnors (and models) on the GPU
The reason we want our tensors/models on GPU is because using GPU results is faster compuataions

In [116]:
# Create a tesnor (default on CPU)
tensor = torch.tensor([1, 2, 3], device = "cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [117]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [118]:
### Moving tensor back to CPU , numpy works only on CPU

#tensor_on_gpu.numpy() == ERROR

In [119]:
# To Fix the GPU tensor with NumpY issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [120]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')