# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [14]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [15]:
# Import torch
import torch

# Create random tensor
random_tensor_A = torch.rand(size = (7, 7))
random_tensor_A, random_tensor_A.shape

(tensor([[0.7665, 0.7236, 0.6076, 0.9120, 0.2732, 0.5075, 0.8072],
         [0.6728, 0.5606, 0.9181, 0.6140, 0.8364, 0.0691, 0.0691],
         [0.0487, 0.5283, 0.9243, 0.0637, 0.6989, 0.0588, 0.1677],
         [0.3295, 0.2967, 0.6477, 0.0807, 0.9944, 0.5729, 0.6743],
         [0.1622, 0.7759, 0.3833, 0.2512, 0.5850, 0.7081, 0.5530],
         [0.3251, 0.5930, 0.3065, 0.3307, 0.3142, 0.7979, 0.1505],
         [0.7171, 0.7592, 0.1678, 0.1202, 0.1670, 0.0770, 0.9198]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [16]:
# Create another random tensor
random_tensor_B = torch.rand(size=(1, 7))
# Perform matrix multiplication
transposed_random_tensor_B = random_tensor_B.T
torch.matmul(random_tensor_A, transposed_random_tensor_B)

tensor([[2.4390],
        [2.1863],
        [1.2619],
        [1.3251],
        [1.1976],
        [1.1459],
        [1.4836]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
torch.manual_seed(3)

# Create two random tensors
random_tensor_C = torch.rand(size = (7, 7))
random_tesnor_D = torch.rand(size = (1, 7))

# Matrix multiply tensors
multiplied_tensor = torch.matmul(random_tensor_C, random_tesnor_D.T)
multiplied_tensor, multiplied_tensor.shape

(tensor([[1.1569],
         [2.7528],
         [2.7826],
         [1.8017],
         [0.8425],
         [1.8660],
         [1.6771]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")
# Create two random tensors on GPU
tensor_E  = torch.rand(size = (2, 3)).to(device)
tensor_F = torch.rand(size= (2, 3)).to(device)
tensor_E, tensor_F

Device : cuda


(tensor([[0.3206, 0.9160, 0.7142],
         [0.2773, 0.8548, 0.5356]], device='cuda:0'),
 tensor([[0.1302, 0.2784, 0.1255],
         [0.0859, 0.5122, 0.1417]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_E and tensor_F
#tensor_G = torch.matmul(tensor_E, tensor_F) # Error
tensor_G = torch.matmul(tensor_E, tensor_F.T)
tensor_G, tensor_G.shape

(tensor([[0.3864, 0.5979],
         [0.3413, 0.5376]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
max = torch.max(tensor_E)
# Find min
min = torch.min(tensor_F)
max, min

(tensor(0.9160, device='cuda:0'), tensor(0.0859, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
arg_max = torch.argmax(tensor_E)
# Find arg min
arg_min = torch.argmax(tensor_E)
arg_max, arg_min

(tensor(1, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_H = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_I = tensor_H.squeeze()

# Print out tensors and their shapes
print(tensor_H, tensor_H.shape)
print(tensor_I, tensor_I.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
